name: Init Tags

on:
  workflow_dispatch:

jobs:
  init-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

      - name: Init tags for all modules
        shell: bash
        run: |
          echo "Initializing tags for all modules..."

          find . -type f -name "AssemblyInfo.cs" | while read -r file; do
            module_dir=$(dirname "$file")
            module_name=$(basename "$(dirname "$module_dir")")  # Get parent of /Properties

            version=$(grep -oP 'AssemblyFileVersion\("\K[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' "$file")

            if [ -n "$version" ]; then
              tag="${module_name}/v${version}"
              echo "Checking for tag: $tag"

              if git rev-parse --quiet --verify "refs/tags/$tag" >/dev/null; then
                echo "Tag $tag already exists, skipping."
              else
                echo "Creating and pushing tag: $tag"
                git tag -a "$tag" -m "Initial version for $module_name"
                git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/caspar5911/CI_CSharp_Practice" "$tag"
              fi
            else
              echo "No version found in $file, skipping..."
            fi
          done
